- name: Testing of other deployment 
  become: true
  become_user: root
  hosts: workernode
  tasks:
  - name: install docker and git
    package: name={{item}} state=present  
    loop:
    - git
    - docker
  - name: Start dcoker service
    service: name=docker state=started
  - name: clone git repo
    git:
     repo: https://github.com/Sonal0409/AnsibleDockerDemo.git
     dest: /tmp/demo
  - name: built docker image
    command: chdir=/tmp/demo docker build -t myimage:ansible .